nacos:
  discovery:
    server-addr: 192.168.2.142:8848
  config:
    server-addr: 192.168.2.142:8848
dubbo:
  application:
    name: dubbo-consumer-demo
  registry:
    address: nacos://192.168.2.142:8848
  protocol:
    name: dubbo

    port: -1


demo:
  service:
    version: 1.0.0
    name: demoService

server:
  port: 8081